/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Patient.Bills;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronitchougule
 */
public class DoctorVisitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorVisitJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    private Patient patient;

    public DoctorVisitJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = account;
        this.patient = patient;
        populateBillTable();
    }

    private void populateBillTable() {
        DefaultTableModel model = (DefaultTableModel) BillTable.getModel();

        model.setRowCount(0);

        for (Bills b : patient.getBillsList()) {

            Object[] row = new Object[7];
            row[0] = b.getItemName();
            row[1] = b.getOrganziationType();
            row[2] = b.getItemAmount();
            row[3] = b.getItemStatus();
            row[4] = b.getResult();
            
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BillTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnRequestLabTests = new javax.swing.JButton();
        btnRequestMedicine = new javax.swing.JButton();
        btnRequestBlood = new javax.swing.JButton();
        btnRequestMedicine1 = new javax.swing.JButton();
        btnRequestMedicine2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BillTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Organization", "Ammount", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BillTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1420, 191));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 1402, 10));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 1382, 60));

        btnRequestLabTests.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestLabTests.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRequestLabTests.setForeground(new java.awt.Color(0, 153, 204));
        btnRequestLabTests.setText("Request Lab Tests");
        btnRequestLabTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLabTestsActionPerformed(evt);
            }
        });
        add(btnRequestLabTests, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 200, 60));

        btnRequestMedicine.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestMedicine.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRequestMedicine.setForeground(new java.awt.Color(0, 153, 204));
        btnRequestMedicine.setText("Request Medicines");
        btnRequestMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicineActionPerformed(evt);
            }
        });
        add(btnRequestMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 200, 60));

        btnRequestBlood.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestBlood.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRequestBlood.setForeground(new java.awt.Color(0, 153, 204));
        btnRequestBlood.setText("Request Blood");
        btnRequestBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestBloodActionPerformed(evt);
            }
        });
        add(btnRequestBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 170, 60));

        btnRequestMedicine1.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestMedicine1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRequestMedicine1.setForeground(new java.awt.Color(0, 153, 204));
        btnRequestMedicine1.setText("Ready to Discharge");
        btnRequestMedicine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicine1ActionPerformed(evt);
            }
        });
        add(btnRequestMedicine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 220, 50));

        btnRequestMedicine2.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestMedicine2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRequestMedicine2.setForeground(new java.awt.Color(0, 153, 204));
        btnRequestMedicine2.setText("End Visit");
        btnRequestMedicine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicine2ActionPerformed(evt);
            }
        });
        add(btnRequestMedicine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 380, 120, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestLabTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLabTestsActionPerformed
        // TODO add your handling code here:

        DoctorRequestLabTestJPanel doctorRequestLabTestJPanel = new DoctorRequestLabTestJPanel(userProcessContainer, userAccount, ecoSystem, patient);
        userProcessContainer.add("Request Lab Tests", doctorRequestLabTestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnRequestLabTestsActionPerformed

    private void btnRequestMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicineActionPerformed
        // TODO add your handling code here:

        DoctorRequestMedicineJPanel doctorRequestMedicineJPanel = new DoctorRequestMedicineJPanel(userProcessContainer, userAccount, ecoSystem, patient);
        userProcessContainer.add("Request  Medicine", doctorRequestMedicineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnRequestMedicineActionPerformed

    private void btnRequestBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestBloodActionPerformed
        // TODO add your handling code here:

        DoctorRequestBloodJPanel doctorRequestBloodJPanel = new DoctorRequestBloodJPanel(userProcessContainer, userAccount, ecoSystem, patient);
        userProcessContainer.add("Request Blood", doctorRequestBloodJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestBloodActionPerformed

    private void btnRequestMedicine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicine1ActionPerformed
        // TODO add your handling code here:
        patient.setPatientStatus("Ready to Discharge");
        DoctorWorkAreaJPanel doctor = new DoctorWorkAreaJPanel(userProcessContainer,userAccount,ecoSystem);
        userProcessContainer.add("Request Blood", doctor);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestMedicine1ActionPerformed

    private void btnRequestMedicine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicine2ActionPerformed
        // TODO add your handling code here:
        patient.setPatientStatus("Under Observation");
        DoctorWorkAreaJPanel doctor = new DoctorWorkAreaJPanel(userProcessContainer,userAccount,ecoSystem);
        userProcessContainer.add("Request Blood", doctor);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestMedicine2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillTable;
    private javax.swing.JButton btnRequestBlood;
    private javax.swing.JButton btnRequestLabTests;
    private javax.swing.JButton btnRequestMedicine;
    private javax.swing.JButton btnRequestMedicine1;
    private javax.swing.JButton btnRequestMedicine2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
